### ISSUE TITLE
FizzBuzz in C++

### ISSUE THREAD

**Issue by Magnesiaworld** [Magnesiaworld/Hacktoberfest_2021#14]
Implement this question in C++

Write a Python program which iterates the integers from 1 to 50. For multiples of three print "Fizz" instead of the number and for the multiples of five print "Buzz". For numbers which are multiples of both three and five print "FizzBuzz“

Output:
1
2
Fizz
4
Buzz
Fizz
7
8
Fizz
Buzz
11
Fizz
13
14
FizzBuzz
16
17
Fizz
19
Buzz
Fizz
22
23
Fizz
Buzz
26
Fizz
28
29
FizzBuzz
31
32
Fizz
34
Buzz
Fizz
37
38
Fizz
Buzz
41
Fizz
43
44
FizzBuzz
46
47
Fizz
49
Buzz

Code should be neat and clean. Comments in code is appreciated.

This will ensure no file will be conflict and any number of contributors can work on the same issue.

If you have any query ask in comments below, kindly follow this pattern strictly.

**Comment by Magnesiaworld** [comment]
No need to wait for getting assigned. Just go ahead and Raise PRs after doing the needed code.

**Comment by Keshavop** [comment]
I will solve this issue

**Comment by Magnesiaworld** [comment]
Thank you guys.
Closing this issue as pull request get merged.
