### ISSUE TITLE
Password Guessing Program Python

### ISSUE THREAD

**Issue by Magnesiaworld** [Magnesiaworld/Hacktoberfest_2021#23]
Implement this question in Python

Write a password guessing program to keep track of how many times the user has entered the password wrong. If it is more than 3 times, print "You have been denied access." and terminate the program. If the password is correct, print "You have successfully logged in." and terminate the program.

If you have any query ask in comments below, kindly follow this pattern strictly.

No need to wait for getting assigned. Just go ahead and Raise PRs after doing the needed code.

**Comment by Magnesiaworld** [comment]
Issue pull request get merged as first come first Service rule.

**Comment by keshavgbpecdelhi** [comment]
Hey made a PR @ #29
