### ISSUE TITLE
Program to check whether an alphabet is a vowel or consonant Python

### ISSUE THREAD

**Issue by Magnesiaworld** [Magnesiaworld/Hacktoberfest_2021#24]
Implement this question in Python

Write a Python program to check whether an alphabet is a vowel or consonant.

If you have any query ask in comments below, kindly follow this pattern strictly.

No need to wait for getting assigned. Just go ahead and Raise PRs after doing the needed code.

**Comment by Magnesiaworld** [comment]
Issue pull request get merged as first come first Service rule.

**Comment by kusumpriya19** [comment]
#26  Hey, I solved this issue, please review it.

**Comment by sgaurav37533** [comment]
Please assign me this issue

**Comment by Siddhesh4501** [comment]
Hey I have did it please check #32 !!!
