### ISSUE TITLE
Binary Search C++

### ISSUE THREAD

**Issue by Magnesiaworld** [Magnesiaworld/Hacktoberfest_2021#4]
Implement Binary Search in C++.

Problem: Given an array arr[] of n elements, write a function to search a given element x in arr[].

Examples :

Input : arr[] = {2, 3, 4, 10, 40}
x = 10;
Output : Element is present at index 3
Element is present at index

Input : arr[] = {2, 3, 4, 10, 40}
x = 50;
Output : Element is not present in array
Element x is not present.

Code should be neat and clean. Comments in code is appreciated.

This will ensure no file will be conflict and any number of contributors can work on the same issue.

If you have any query ask in comments below, kindly follow this pattern strictly.

**Comment by Magnesiaworld** [comment]
No need to wait for getting assigned. Just go ahead and Raise PRs after doing the needed code.

**Comment by shubhamnag14** [comment]
can i solve this issue

**Comment by shubhamnag14** [comment]
Can I upload other algorithms in c++ or python

**Comment by Magnesiaworld** [comment]
@shubhamnag14 Sorry I reviewed your pull request. Do check-out my comment. 

Don't worry many more issues are coming

Keep Contributing

**Comment by Magnesiaworld** [comment]
Thank you guys.

Closing this issue as pull request get merged.

Keep Contributing ✌
