### ISSUE TITLE
Fix About Page Footer Sync_Real-Estate

### ISSUE THREAD

**Issue by Magnesiaworld** [Magnesiaworld/Hacktoberfest_2021#42]
Fix footer of About Page and make it responsive

![image](https://user-images.githubusercontent.com/78963574/135855873-670d98f6-51dc-45b5-9af5-d082a707cba0.png)

**Comment by Harshil-Jani** [comment]
@Magnesiaworld Can I Try Fixing this ?

**Comment by nirmalKumawat-kgp** [comment]
Can you assign this to me?
